import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/scheduling">Scheduling</Link>
        </li>
        <li>
          <Link to="/tasklist">Tasklist</Link>
        </li>
        <li>
          <Link to="/teambuilder">TeamBuilder</Link>
        </li>
        <li>
          <Link to="/automatedprioritisation">AutomatedPrioritisation</Link>
        </li>
        <li>
          <Link to="/leavetracker">LeaveTracker</Link>
        </li>
        <li>
          <Link to="/prioritise">Prioritise</Link>
        </li>
        <li>
          <Link to="/reviewapproval">ReviewApproval</Link>
        </li>
        <li>
          <Link to="/taskallocator">TaskAllocator</Link>
        </li>
        <li>
          <Link to="/taskblocker">TaskBlocker</Link>
        </li>
        <li>
          <Link to="/savedcards">SavedCards</Link>
        </li>
        <li>
          <Link to="/taskviews">TaskViews</Link>
        </li>
        <li>
          <Link to="/taskallocatorone">TaskAllocatorOne</Link>
        </li>
        <li>
          <Link to="/signuploginmodule">SignupLoginModule</Link>
        </li>
        <li>
          <Link to="/termsandconditions">TermsAndConditions</Link>
        </li>
        <li>
          <Link to="/useraccount">UserAccount</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
